# Generated by Django 5.0.6 on 2026-06-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_importjob_id_alter_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("running", "RUNNING"),
                    ("completed", "COMPLETED"),
                    ("failed", "FAILED"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "FOOD"),
                    ("transport", "TRANSPORT"),
                    ("utilities", "UTILITIES"),
                    ("entertainment", "ENTERTAINMENT"),
                    ("health", "HEALTH"),
                    ("travel", "TRAVEL"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "COMPLETED"),
                    ("pending", "PENDING"),
                    ("failed", "FAILED"),
                ],
                max_length=16,
            ),
        ),
    ]
